name: Notify IndexNow

on:
  push:
    paths:
      - '
      - 'kriptoobmennik-v-Moskve-top-4-bezopasnyh-platform-po-otzyvam/**'   # путь к твоему проекту
      - 'ExnodeIndexNow.json'                 # путь к JSON-файлу

jobs:
  indexnow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Send IndexNow request
        run: |
          curl -X POST "https://api.indexnow.org/indexnow" \
               -H "Content-Type: application/json" \
               -d @data.json
